### ISSUE TITLE
Request: piston tracks

### ISSUE THREAD

**Issue by Jacky2611** [CovertJaguar/Railcraft#379]
Ever wanted to add new carts to a train without having to work at the public train station? Do you want to keep tourists away from the fusion reactor you use to charge your trains? Or are you simply afraid that other players could steal your fully boarded loot train?
I have the perfect solution for you: piston-tracks!
Using them you can lift a whole train to a 4 blocks higher/lower track in just a few seconds. 

These tracks are around 1 block tall and require energy to move up or down.  Due to the development of new ultra awesome remote technology they come together with a nicely looking black remote controller that can be connected to an infinite number of them.

I won't spend my time to code something like this before the 1.8 update since it's going to break nearly all rendering related stuff.(yeahh, a new resource pack system...again! Who needs the good old TESR system?)
When you read this and there is no registered patent from me feel free to add this feature on your own. (But keep in mind that you used research information from Jacky Industries. :P)

**Comment by ssotangkur** [comment]
Is this possible already with redstone and pistons or do the tracks pop off when you try to lift them?

**Comment by CovertJaguar** [comment]
Vanilla Tracks can be pushed around by pistons, but moving it more than one block is a complex process.

**Comment by liach** [comment]
How about pushing up and down? I think this's the point.

**Comment by Forecaster** [comment]
They can't be moved up or down. They pop off.

**Comment by ssotangkur** [comment]
So when you say a "whole train", it sounds complicated for a single track to accomplish that, especially since carts/locos are technically longer than a single track. There's also a lot of corner-cases that would have to be dealt with (like what happens when you lift half a train, or a train is getting squished by a lowering track).

I think if the rails don't pop off, you might be able to use something like Framez (http://minecraft.curseforge.com/mc-mods/76118-framez) to do what you want.

IMHO, this doesn't seem like a very realistic addition since nothing like this is available in the real world (i guess you can make the same argument about laser rails, but at least these exist in fiction like Tron). I'd say that if it only takes minor tweaks to get rails to work w/ Framez, then that seems like a worthwhile addition that adds lots of other creative uses. Making a single special rail that only goes up and down, to me, seems a bit out of place compared to the other rails that we have. Just my 2 cents.

**Comment by XFactHD** [comment]
This is already possible with Funky Locomotion, the frames move empty tracks as well as tracks with carts.

**Comment by CovertJaguar** [comment]
This is beyond the scope of Railcraft, use one of the various frame mods.
