### ISSUE TITLE
[Suggestion] RF energy carts

### ISSUE THREAD

**Issue by scj643** [CovertJaguar/Railcraft#397]
These carts would act just like the IC2 bat box carts, except for RP.

**Comment by Carbon-Ghost** [comment]
Perhaps crafted with the electric locomotive with some RF converters blocks ?  ( as RF can't be used for motors, needing a bridge to make it work with electric motors ? ).

**Comment by CovertJaguar** [comment]
The RF Storage Cart will not be able to power Electric Locomotives. The Charge Battery Cart however will.

**Comment by Carbon-Ghost** [comment]
I understood that, but what I mean't was that maybe make the RF cart a modified electric cart, that have an internal RF converter ? ( only accepts RF due to modification ). 

So the model would look like the electric locomotive with the fancy RF converter block texture on the sides ? And the crafting recipe maybe the E-loco w/ RF converter blocks ? ( just giving ideas ).

**Comment by mskurnik** [comment]
I would have to say this would be a nice addon for Railcraft as we are not using any form of IC2 power on our server.  It seems that IC2 power is starting to become obsolete actually with most mods that I have come across switching to RF and leaving IC2 legacy support.

**Comment by CovertJaguar** [comment]
Implemented.
