### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by aldra2012** [CovertJaguar/Railcraft#573]
http://pastebin.com/0t60ezzE

**Comment by unpure** [comment]
Hey there.
I'm currently trying to update my modpack.
Because extrautilities needs atleast forge 10.13.3.1355 i updated it too.
There is no problem with forge 10.13.2.1291
The problem from this issue seems to be not realy related to railcraft.
It only happens on the latest versions of forge and not only with railcraft!
After removing railcraft from my mods folder i got almost the same crash with MFR.
With MFR its milk instead of steam but its the same problem.
It seems like forge changed something on the latest versions because almost every mod that adds fluids (like RC steam or MFR milk) seems to have this problem.

**Comment by aldra2012** [comment]
well thank you i will just downgrade extra utilities then to fix the problem cuz i hate running into more issues
