### ISSUE TITLE
Incompatibility with CraftGuide

### ISSUE THREAD

**Issue by vpontin** [CovertJaguar/Railcraft#679]
Hi!

I'm having issues with railcraft and craftguide (https://github.com/Uristqwerty/CraftGuide/).

After installing railcraft, the item list shows a "null" block first, and the search box don't work anymore.

![image](https://cloud.githubusercontent.com/assets/3485505/9445069/8f85d394-4a60-11e5-8df4-5ecc9d853b9d.png)

Removed railcraft, everything runs fine. No errors appears in log. It don't crash the game, but is very annoying.

Is there a way to fix this in your side?

**Comment by Aleszp** [comment]
Use previous CrfatGuide version. Worked for me.

**Comment by CovertJaguar** [comment]
I'd report this to @Uristqwerty. I'm not sure what is happening here.

**Comment by Uristqwerty** [comment]
I am not entirely sure how to reproduce the problem (interactions with other mods? Config changes? Specific versions? One or more of the above coupled with a specific language choice? Affected by Forge version?), though I tried making searches more null-resistant a while ago, which might have worked to at least reduce the impact.

If I ever do discover the root cause, I'll try to remember to post it here.
