### ISSUE TITLE
Improved Loaders and Unloaders

### ISSUE THREAD

**Issue by ZeekDaGeek** [CovertJaguar/Railcraft#709]
Using loaders and unloaders at the moment are infuriating, they feel very old and like they're missing features you would expect.

First off redstone interactions:

OUTPUT
The Loaders and Unloaders don't seem to interact with redstone the way you would expect, they will not output redstone when finished to anything other than vanilla redstone and railcraft tracks it seems. I've attempted to use Ender IO Redstone Conduits and they don't work, tried color redstone and it didn't seem to work. Infact the block itself doesn't seem to emit redstone in such a way that you can put a redstone torch on it. This has been limiting how I've trying to use trains to transport things around the world, but it's something I've been able to work around.

http://zeekdageek.tv/ss/p7KXx.png

I also attempted to read how full a loader was based on a comparator output but they don't seem to supply any information that way.

INPUT
It doesn't seem that you can lock the transfer of loaders and unloaders by supplying a redstone signal to them. If you want to specifically load certain chest carts in a train with a certain item it seems to be impossible because you will suck things from every cart that passes or spew items across chest carts as they go under.

There are ways to do one way signals, it's not like a block supplying and receiving would be a problem with repeaters or with the ability to use colored input methods with Ender IO or Bundled Cables.

Some of the Redstone problems can also be solved by better filters:

Cart can be named now. When you break a cart the name is maintained. You can put a named cart into the slots of the Loaders and Unloaders but they're not actually respected. An example where this would make sense would be naming the Tank supplying the locomotive "Water Tank" that way you only fill that one with water instead of every other tank cart.

Inverted Filters would also be a nice option. Here's an example where it would be useful: Things like Mekanism have plenty of liquids to move around, however, they don't into buckets (Sulfuric Acid buckets wouldn't even make sense). I'm attempting to move Hydrogen Chloride from a desert biome far off to my main base, which makes a Water Tank attached to the train make sense. When the Train arrives at the base every Fluid unloader will pull water from the Water Tank and it prevents the Hydrogen Chloride from ever being unloaded. If there was an inverted filter for Water it would prevent that.

**Comment by Vexatos** [comment]
For what it's worth, you can probably use BuildCraft gates for now to circumvent the Comparator issue.

**Comment by CovertJaguar** [comment]
#### Redstone Output:
This is due to technical issues. Emitting a redstone signal at all times creates other headaches (tracks and redstone are weird). I purposefully limit it to only outputting if I know something that accepts redstone is present in order to reduce issues during the 99.9% of times when redstone output is undesirable. Unfortunately there is no standard interface to determine if a block accepts redstone input. The only other solution is to add yet another button to the GUI to manually turn redstone output on/off. This is a bit of a pain and increases the GUI complexity.

#### Comparator
This is a valid complaint.

#### Redstone Input
This might be possible to do with Buildcraft gates, there are some actions that Loaders provide. I've had problems in the past with blocks that both accept and emit redstone. Maybe its better these days I don't know. But again, it would require another button in the GUI probably.

#### Filters
The lack of containers for certain fluids isn't really anything I can fix. And again, I'd rather not increase GUI complexity by adding more buttons.
