### ISSUE TITLE
Is there any config option to remove or configure Carts Weight , especially , energy carts?

### ISSUE THREAD

**Issue by Xpycteem** [CovertJaguar/Railcraft#752]
Ok , that's a little bit annoying , cause , you can "Link" , 3 or 4 storage carts together and locomotive is going to run fast , but if u are going to "Link" to Locomotive one energy cart(MFE carts etc.) it speed is going to be very slow . Can anyone help?

**Comment by Landrash** [comment]
What your looking for is the drag value for the carts. Each cart adds a certain amount of drags and most carts use a standard value.  
Railcraft also changes the drag value for the normal minecarts and that can be disabled in the config. As far as I know there's no option to change the drag value of a specific cart in the config.

**Comment by Xpycteem** [comment]
Yep , you are right , but , it is works a little bit glitchy . I am gonna attach a gif...
![Uploading ezgif.com-video-to-gif.gif…]()

**Comment by Xpycteem** [comment]
Yep , you are right , but this works a little bit glitchy

**Comment by Xpycteem** [comment]
Hello? Can anyone help?

**Comment by eyeballcode** [comment]
With the current Railcraft configuration files, it doesn't seem possible. What you could try is linking up a few carts together. Maybe that would work

**Comment by Xpycteem** [comment]
Nope , i tryed to link up 6 diffirent carts and nothing happened , train still runs very slow and when i shut it down it runs forward for a second , like on a gif .

**Comment by Landrash** [comment]
It running forward a bit after being powered of is intended behavior. If the train got some momentum it wont just stop. Turning it of isn't a emergency brake. If you need it to stop quickly try to combine tracks.
One to turn it of and one to lock it in place.

**Comment by eyeballcode** [comment]
Oh, sorry. I think I misunderstood you the first time. You could try using a [locking track](http://railcraft.info/wiki/track:locking_track) to stop your train. I tested it and even when going at full speed, the train stops immediately

**Comment by Xpycteem** [comment]
Come one guys , all for you get me right for the first time ... I was talking that the config option is not working . And i gaved u an example .There is a glitch when you turn your train of it is like gets a speed boost ...

**Comment by Landrash** [comment]
It's not really getting a speed boost. Locomotive stops pulling, cart
catches up and bumps into locomotive. Whole train jumps forward before
losing its momentum.

IDon't think there's a workaround for this since it's partly based on
minecrafts cart physics and you get some more quirks with the coupling of
trains.

**Comment by Xpycteem** [comment]
Ok , so why does it still runs very slow ? My adjustDrag=false ...

**Comment by Landrash** [comment]
adjustDrag just adjust drag of vanilla minecarts to make trains more viable if I've understood it correctly.

**Comment by Xpycteem** [comment]
And , what about MFE cart ? How to change drag value for it?

**Comment by kamilosxd678** [comment]
This is really annoying - option for disabling it is a MUST HAVE

**Comment by Xpycteem** [comment]
I agree !

**Comment by CovertJaguar** [comment]
Tell me why you believe that? Because in my opinion this is an absolutely necessary balance concession to allowing you to transport power via battery.

**Comment by kamilosxd678** [comment]
Yes, having a battery powered railway would be OP if done right, but what if server admin wants to provide a railway of his own - this is simply annoying. Second of all the incompability of H.S. tracks and electric locomotives is just hard to deal with - if you want to use them, then you have to equip your electric locomotive with battery cart, but the drag of battery carts just kills the idea at the very beginning. Switching this option on and off will provide more configurability for the server owners without them need to fork your code and modify it.

Other way to deal with it - imho - would be adding TWO options in config:
One - Disable drag
Two - Disable powering electric locomotive from attached battery carts
With two options enabled, we could still eliminate OP-ness of these carts, but simultaneously allow moving electricity via railway. (btw, MFSU carts should get back to railcraft)

In my case I've created railway system on my server where you can use computer to fetch train on rail station. The coal powered carts were working awesome, but fetching them took too much time because of them needing to heat themselves first in order to work. This is really painfull and I think a system allowing of external steam providing would really help in getting them on railstation platform ASAP.

**Comment by CovertJaguar** [comment]
The H.S. Track problem is better solved by adding an electric version (or making the existing one electric) or adding overhead wires.

The admin issue may be better solved by adding a infinite power cart with no recipe.

**Comment by Xpycteem** [comment]
Well , all of thet sounds great , but , what if i don't won't use Electric rails? . I do have enought energy , what shoud i do then ? The electic locomotives are great , but they are useless , when it comes to dealing with energy carts and speed .
It is very importand to have a good comunication between mod dev. and mod user . I have a lot of trubles with Steam Locomotives . They are hart to use , just because they use Steam , on the other hand , there is a Energy Loco. , but i can't use it , canuse i don't won't to use Electric rails and cause of it speed .
in conclusion , there are twi variants what we can do : 
1)Addetion an electric rails in all editions(H.S , Wooden , Reinf. and ect.) - this option is hard to make and wood not give anything new to a mod .
2)To Make a config option , grab option , that is going to : 
     a)Remove grag at all
     b)Remove drag from energy carts
     c)Make a better config files , with manual drag options
In my opinion the third one "c)" - best one . Mods needs to be flexible , you , as a dev. need to give people what they won't , only then they are going to respect mods and use them more .
Hope you get me here :3

**Comment by XFactHD** [comment]
"Mods needs to be flexible , you , as a dev. need to give people what they won't , only then they are going to respect mods and use them more ." This is not your mod, it is CovertJaguar's mod, he decides what is added and not you, he does not need to give you what you want, only if he wants it to be added.

**Comment by Xpycteem** [comment]
I understand , we are not forcing him to add something new . Drag is allready exist , it just needs to be more configurabe :3

**Comment by Forecaster** [comment]
How are steam locomotives hard to use... you put in fuel and water and they go...

**Comment by kamilosxd678** [comment]
@Forecaster Yes, but it is impossible to create good system that will fetch trains on demand with prefueled, preheated ready-to-go locomotives. Which you can easily do with electric locomotives, as they do not use energy while standing still, so you can have couple of tracks with energy fillers for energy carts.

@Xpycteem Exactly as you say. These things are already in the code, all that needs to be done is just getting them from config instead of this already existing hardcodes.

@CovertJaguar Electric H.S. Tracks I think would be the best option imho. Overhead lines are tricky, because creating a nice design that wouldn't ruin the overall looks could be very hard to achieve and from the code point of view it would create need to implement whole new feature, while adding electric H.S. is a matter of copy-pasting two classes and merging them into one.

Second of all infinite energy cart is still an energy cart so H.S. tracks with speed of an old lady with zimmer kind of defeats the whole purpose.

Thirdly again from the programmers point of view adding customizable drag in config is a matter of 30min more or less.

Lastly - MFSU carts could also be disabled from config (I think there even still is option for that even though the MFSU carts are removed from code.

I think I could provide my approach for that problems as a pull requests if you would be interested.

**Comment by Forecaster** [comment]
If you want on-demand locomotives use firestones for fuel. They'll heat up very quickly.

**Comment by kamilosxd678** [comment]
@Forecaster Thank you, I didn't know that.

**Comment by CovertJaguar** [comment]
An Infinite Power Admin cart would probably only be capable of powering locomotives (no offloading energy) and would likely not have the same drag restrictions.

**Comment by kamilosxd678** [comment]
@CovertJaguar Actual implementation allows to use Admin Feeder Station which can also help, but doesn't work good with H.S. Track

**Comment by Xpycteem** [comment]
So , are we going to have such config option in 1.7.10? Please?)
